---
engines:
  fixme:
    enabled: true
  gofmt:
    enabled: false
  golint:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD030:
        enabled: false
ratings:
  paths:
  - "**.go"
exclude_paths:
- "**/vendor/**/*"
- "**/mocks/**/*"
- "**/*_test.go"
