// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Count                uint32   `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Person) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type MyReply struct {
	Thereply             string   `protobuf:"bytes,1,opt,name=thereply,proto3" json:"thereply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyReply) Reset()         { *m = MyReply{} }
func (m *MyReply) String() string { return proto.CompactTextString(m) }
func (*MyReply) ProtoMessage()    {}
func (*MyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *MyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyReply.Unmarshal(m, b)
}
func (m *MyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyReply.Marshal(b, m, deterministic)
}
func (m *MyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyReply.Merge(m, src)
}
func (m *MyReply) XXX_Size() int {
	return xxx_messageInfo_MyReply.Size(m)
}
func (m *MyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MyReply.DiscardUnknown(m)
}

var xxx_messageInfo_MyReply proto.InternalMessageInfo

func (m *MyReply) GetThereply() string {
	if m != nil {
		return m.Thereply
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterType((*MyReply)(nil), "main.MyReply")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x4d, 0x0a, 0xc2, 0x30,
	0x10, 0x46, 0x89, 0xfd, 0x51, 0x07, 0x14, 0x19, 0x5c, 0x04, 0x57, 0xa1, 0x20, 0x64, 0xe5, 0xc6,
	0x73, 0x08, 0x92, 0x1b, 0x44, 0x19, 0xda, 0x42, 0xf3, 0x43, 0x12, 0x17, 0xbd, 0xbd, 0x24, 0x11,
	0x77, 0xef, 0x3d, 0x06, 0xe6, 0x83, 0xa3, 0xa1, 0x18, 0xf5, 0x48, 0xf1, 0xe6, 0x83, 0x4b, 0x0e,
	0x5b, 0xa3, 0x67, 0x3b, 0x78, 0xe8, 0x9f, 0x14, 0xa2, 0xb3, 0x88, 0xd0, 0x5a, 0x6d, 0x88, 0x33,
	0xc1, 0xe4, 0x5e, 0x15, 0xc6, 0x13, 0x34, 0x7a, 0x24, 0xbe, 0x11, 0x4c, 0x76, 0x2a, 0x23, 0x9e,
	0xa1, 0x23, 0xa3, 0xe7, 0x85, 0x37, 0xe5, 0xac, 0x4a, 0xae, 0x7e, 0x72, 0x96, 0x78, 0x5b, 0x6b,
	0x91, 0x5c, 0xdf, 0xee, 0x63, 0x13, 0xef, 0x04, 0x93, 0x07, 0x55, 0x65, 0xb8, 0xc2, 0xf6, 0xb1,
	0x2a, 0xf2, 0xcb, 0x8a, 0x17, 0xd8, 0xa5, 0x89, 0x42, 0xe6, 0xdf, 0xdb, 0xbf, 0xbf, 0xfa, 0xb2,
	0xf2, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x7d, 0xe7, 0x1b, 0xb7, 0x00, 0x00, 0x00,
}
